export const exerciseList = [
  { id: 1, name: "Surya Namaskar", reps: 20, img: "https://media0.giphy.com/media/PamQm28534SYM/200.webp?cid=ecf05e476bdaeopk8zefxw6pb4b4o4qksqthmfzr4x0gk251&rid=200.webp&ct=g" },
  { id: 2, name: "Pushups", reps: "10-25", img: "https://media.giphy.com/media/tsTsgT7v6wy5hYXI9U/giphy.gif" },
  { id: 3, name: "Jumping Jacks", reps: 30, img: "https://media.giphy.com/media/ckMk3RKUK29lziaspI/giphy.gif" },
  { id: 4, name: "Burpies", reps: 10, img: "https://media.giphy.com/media/l41YgS3UPP5Qjwr8Q/giphy.gif" },
  { id: 5, name: "Mountainclimbs", reps:"00:45", img: "https://media.giphy.com/media/D8PNyQTvanRe0/giphy.gif" },
  { id: 6, name: "Situps", reps: 20, img: "https://media.giphy.com/media/35EH7kLQiMM1YWYmUI/giphy.gif" },
  { id: 7, name: "One handed planks with rotation", reps:25, img: "https://media.giphy.com/media/yIv8U59Lhj2aQ/giphy.gif" },
  { id: 8, name: "Alternate lunges", reps: 30, img: "https://media.giphy.com/media/cXHxOJu8vEwhoApxjy/giphy.gif" },
  { id: 9, name: "Pushups using sliders", reps: 15, img: "https://media.giphy.com/media/VIn8JLRfc56PrSI7uj/giphy.gif" },
  { id: 10, name: "Hipthrusts using sliders", reps: 25, img: "https://media.giphy.com/media/fWqRy6Uj0OZeBeQfoZ/giphy.gif" },
  { id: 11, name: "Reverse Snowangels", reps: 30, img: "https://media.giphy.com/media/UX5tFptTkruo6xqp65/giphy.gif" },
  { id: 12, name: "Dumbell Tricep press", reps: 25, img: "https://media.giphy.com/media/9MIIsyYvHTunm84NNl/giphy.gif" },
  { id: 13, name: "Slow mountain climbers", reps: 20, img: "https://media.giphy.com/media/w8sTeE7D0sFdKIO8Rk/giphy.gif" },
  { id: 14, name: "Leg lift with hip raises", reps: 15, img: "https://media.giphy.com/media/LRflK43fTSbqiMFEa4/giphy.gif" },
  { id: 15, name: "situps", reps:20 , img: "https://media.giphy.com/media/ZYWYS0w1uyB3h55w9h/giphy.gif" },
  { id: 16, name: "high plank hold", reps: "01:20", img: "https://media.giphy.com/media/3PywN1RF3eLyVTgzTw/giphy.gif" },
  { id: 17, name: "modified tabletop hold", reps: "01:20", img: "https://media.giphy.com/media/1gdx2vgrpOX2p1MqSm/giphy.gif" },
  { id: 18, name: "narrow squats with weights", reps: 25, img: "https://media.giphy.com/media/Sq3ZBjTCRmx4PQedQn/giphy.gif" },
  { id: 19, name: "wall sit squat", reps: "01:20", img: "https://media.giphy.com/media/5hqs5R78mB5thn3eSc/giphy.gif" },
  { id: 20, name: "skater hops", reps: "00:45", img: "https://media.giphy.com/media/wqMYREwqjGeIYbtuBK/giphy.gif" },
  { id: 21, name: "jump squats", reps: 25, img: "https://media.giphy.com/media/xU1ryd1OkMzbh9VwDR/giphy.gif" },
  { id: 22, name: "crunch kicks", reps: 20, img: "https://media.giphy.com/media/sWCj7fzlhMgodcO4KL/giphy.gif" },
  { id: 23, name: "Good Going", reps: "all day", img: "https://tenor.com/view/squishiverse-squishiland-squishies-slimes-squishie-gif-25483441" },
  // { id: 24, name: "Exercise 8", reps: 7.99, img: "" },
  // { id: 25, name: "Exercise 8", reps: 7.99, img: "" },
  // { id: 26, name: "Exercise 8", reps: 7.99, img: "" },
];